server:
  port: ${EUREKA_SERVER_PORT:8761}

spring:
  application:
    name: ${EUREKA_SERVER_NAME:eureka-server}

eureka:
  client:
    # 表示是否注册自身到eureka服务器
    # register-with-eureka: false
    # 是否从eureka上获取注册信息
    # fetch-registry: false
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8764/eureka/,http://localhost:8765/eureka/