server:
  port: 8765

spring:
  application:
    name: eureka-server3

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8764/eureka/,http://localhost:8765/eureka/